default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  user: postgres

development:
  <<: *default
  database: find-out-with-forms_development

test:
  <<: *default
  database: find-out-with-forms_test

production:
  <<: *default
  database: find-out-with-forms_production
